name: Deploying the container to AWS ec2 machine
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - adding-ec2-deploy
env:
  # Define environment variables using secrets
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  AWS_PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY }}
jobs:
  # Job to build Docker image and push to DockerHub
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./Source
          push: true
          dockerfile: ./Dockerfile
          tags: pratik180797/bsc23grassroots:tagname
  # Job to deploy Docker image to AWS       
  deploy:
    needs: build  # This job depends on the 'build' job
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ env.DOCKERHUB_TOKEN }}
    - name: Set permissions for private key
    # Write AWS private key to a file and set permissions
      run: |
        echo "${{ env.AWS_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem
    - name: Pull Docker image
    # SSH into AWS EC2 instance, pull Docker image from DockerHub
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-18-234-62-236.compute-1.amazonaws.com 'sudo docker pull pratik180797/bsc23grassroots:tagname'
    - name: Stop running container
    # Stop and remove existing Docker container on AWS EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-18-234-62-236.compute-1.amazonaws.com 'sudo docker stop bsc23grassroots || true'
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-18-234-62-236.compute-1.amazonaws.com 'sudo docker rm bsc23grassroots || true'
    - name: Run new container
    # Run a new Docker container on AWS EC2 with the updated image
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@ec2-18-234-62-236.compute-1.amazonaws.com 'sudo docker run -d --name bsc23grassroots -p 8000:8000 pratik180797/bsc23grassroots:tagname'
