name: Load Testing

on:
  push:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install
        working-directory: ./convention_center_booking_system

      - name: Build the React app
        run: npm run build
        working-directory: ./convention_center_booking_system

      - name: Run JMeter Load Test
        run: |
          # Download JMeter (adjust the version as needed)
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.3.tgz
          tar -xzf apache-jmeter-5.4.3.tgz
         
          # Run the JMeter test plan
          ./apache-jmeter-5.4.3/bin/jmeter -n -t path/to/your-test-plan.jmx
