name: Load Testing

on:
  push:
    branches:
      - main

jobs:
  load-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java (required for JMeter)
        uses: actions/setup-java@v1
        with:
          java-version: '11'  

      - name: Install JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.4.3.tgz
          tar -xzf apache-jmeter-5.4.3.tgz
          echo "JMeter installed successfully"

      - name: Run JMeter Load Test
        run: |
          apache-jmeter-5.4.3/bin/jmeter -n -t ./convention_center_booking_system/jmeter.jmx -l test-results.jtl
          
      - name: Upload Test Results as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: jmeter-test-results
          path: test-results.jtl
